// This file is generated by kconfig_compiler from kdiffext.kcfg.
// All changes you do to this file will be lost.
#ifndef SETTINGS_H
#define SETTINGS_H

#include <kconfigskeleton.h>
#include <kdebug.h>

#include <limits.h>
class Settings : public KConfigSkeleton
{
  public:

    static Settings *self();
    ~Settings();


    /**
      Get max_filename_length
    */
    static
    int max_filename_length()
    {
      return self()->mMax_filename_length;
    }


    /**
      Get Compare command
    */
    static
    QString diff_command()
    {
      return self()->mDiff_command;
    }


    /**
      Get Compare tool supports KIO
    */
    static
    bool diff_kio()
    {
      return self()->mDiff_kio;
    }


    /**
      Get Compare folders
    */
    static
    bool diff_folders()
    {
      return self()->mDiff_folders;
    }


    /**
      Get 3-way compare command
    */
    static
    QString diff3_command()
    {
      return self()->mDiff3_command;
    }


    /**
      Get 3-way compare tool supports KIO
    */
    static
    bool diff3_kio()
    {
      return self()->mDiff3_kio;
    }


    /**
      Get Compare folders
    */
    static
    bool diff3_folders()
    {
      return self()->mDiff3_folders;
    }

    static
    void writeConfig()
    {
      static_cast<KConfigSkeleton*>(self())->writeConfig();
    }
  protected:
    Settings();
    static Settings *mSelf;


    // general
    int mMax_filename_length;

    // diff
    QString mDiff_command;
    bool mDiff_kio;
    bool mDiff_folders;

    // diff3
    QString mDiff3_command;
    bool mDiff3_kio;
    bool mDiff3_folders;

  private:
};

#endif

