// This file is generated by kconfig_compiler from kdiffext.kcfg.
// All changes you do to this file will be lost.

#include "settings.h"

#include <kstaticdeleter.h>

Settings *Settings::mSelf = 0;
static KStaticDeleter<Settings> staticSettingsDeleter;

Settings *Settings::self()
{
  if ( !mSelf ) {
    staticSettingsDeleter.setObject( mSelf, new Settings() );
    mSelf->readConfig();
  }

  return mSelf;
}

Settings::Settings(  )
  : KConfigSkeleton( QString::fromLatin1( "kdiffextrc" ) )
{
  mSelf = this;
  setCurrentGroup( QString::fromLatin1( "general" ) );

  KConfigSkeleton::ItemInt  *itemMax_filename_length;
  itemMax_filename_length = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "max_filename_length" ), mMax_filename_length, 63 );
  itemMax_filename_length->setMinValue(20);
  addItem( itemMax_filename_length, QString::fromLatin1( "max_filename_length" ) );

  setCurrentGroup( QString::fromLatin1( "diff" ) );

  KConfigSkeleton::ItemPath  *itemDiff_command;
  itemDiff_command = new KConfigSkeleton::ItemPath( currentGroup(), QString::fromLatin1( "command" ), mDiff_command );
  addItem( itemDiff_command, QString::fromLatin1( "diff_command" ) );
  KConfigSkeleton::ItemBool  *itemDiff_kio;
  itemDiff_kio = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "use_kio" ), mDiff_kio, false );
  addItem( itemDiff_kio, QString::fromLatin1( "diff_kio" ) );
  KConfigSkeleton::ItemBool  *itemDiff_folders;
  itemDiff_folders = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "compare_folders" ), mDiff_folders, false );
  addItem( itemDiff_folders, QString::fromLatin1( "diff_folders" ) );

  setCurrentGroup( QString::fromLatin1( "diff3" ) );

  KConfigSkeleton::ItemPath  *itemDiff3_command;
  itemDiff3_command = new KConfigSkeleton::ItemPath( currentGroup(), QString::fromLatin1( "command" ), mDiff3_command );
  addItem( itemDiff3_command, QString::fromLatin1( "diff3_command" ) );
  KConfigSkeleton::ItemBool  *itemDiff3_kio;
  itemDiff3_kio = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "use_kio" ), mDiff3_kio, false );
  addItem( itemDiff3_kio, QString::fromLatin1( "diff3_kio" ) );
  KConfigSkeleton::ItemBool  *itemDiff3_folders;
  itemDiff3_folders = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "compare_folders" ), mDiff3_folders, false );
  addItem( itemDiff3_folders, QString::fromLatin1( "diff3_folders" ) );
}

Settings::~Settings()
{
  if ( mSelf == this )
    staticSettingsDeleter.setObject( mSelf, 0, false );
}

